# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ jethome ]
  pull_request:
    branches: [ jethome ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: ./compile_and_convert_to_s905w_and_a113x.sh
      
    - name: Archive img artifacts
      uses: actions/upload-artifact@v2
      with:
        name: images
        path: output/images

    - name: Archive deb artifacts
      uses: actions/upload-artifact@v2
      with:
        name: deb
        path: output/debs
